import { useEffect, useMemo, useState } from 'react'
import { api } from '../api/client'
import { ApiImage } from '../components/ApiImage'

type Student={id:number;full_name:string;about_me?:string|null;avatar_file_id?:string|null;metro?:string|null;average_rating?:number|null;teachers?:Array<{id:number;full_name:string}>;works_count?:number}
type Homework={id:number;lesson_number?:number|null;haircut_name?:string|null;file_id?:string|null;file_url?:string|null;text_content?:string|null;rating?:number|null;comment?:string|null;status:string}
const demoImages=new Set(['demo-homework-crop.png','demo-homework-fade.png','demo-homework-beard.png','demo-student-barber.png','demo-teacher-barber.png'])
const workImage=(work:Homework)=>work.file_url||(work.file_id&&demoImages.has(work.file_id)?`/${work.file_id}`:null)

export function GuestPortfolioPage(){
  const[students,setStudents]=useState<Student[]>([]);const[works,setWorks]=useState<Record<number,Homework[]>>({});const[selected,setSelected]=useState<number|null>(null);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true)
  useEffect(()=>{void api.get('/guest/portfolio-students').then(async(response)=>{const items=response.data?.data?.students||[];setStudents(items);const portfolios=await Promise.all(items.map(async(student:Student)=>{const result=await api.get(`/guest/students/${student.id}/portfolio`);const data=result.data?.data||{};if(data.student)setStudents((current)=>current.map((item)=>item.id===student.id?{...item,...data.student}:item));return[student.id,data.homeworks||[]]as const}));setWorks(Object.fromEntries(portfolios))}).finally(()=>setLoading(false))},[])
  const visible=useMemo(()=>students.filter((student)=>student.full_name.toLocaleLowerCase('ru').includes(query.trim().toLocaleLowerCase('ru'))),[students,query]);const active=students.find((s)=>s.id===selected)
  return <section className="fi"><div className="portfolio-hero"><span className="eyebrow">MADCAP Barber Academy</span><h2>Портфолио учеников</h2><p>Реальные работы, проверенные преподавателями академии.</p></div><label className="search-field floating-search"><span>Поиск мастера</span><input type="search" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Имя ученика"/></label>{loading&&<p className="state-message">Загружаем портфолио…</p>}<div className="portfolio-grid">{visible.map((student)=>{const list=works[student.id]||[];const cover=list[0];return <button className="portfolio-card portfolio-button" type="button" key={student.id} onClick={()=>setSelected(student.id)}>{cover&&<ApiImage className="portfolio-cover" src={workImage(cover)} apiPath={!workImage(cover)&&cover.file_id?`/guest/homeworks/${cover.id}/file`:null} alt=""/>}<div className="portfolio-heading"><div className="avatar-placeholder">{student.full_name.slice(0,1)}</div><div><h3>{student.full_name}</h3><p>{student.metro||'Москва'} · {list.length} работ</p>{student.average_rating&&<span className="mini-rating">★ {Number(student.average_rating).toFixed(1)}</span>}</div></div></button>})}</div>{!loading&&!visible.length&&<div className="empty">Портфолио не найдено.</div>}
    {active&&<div className="sheet-backdrop" role="presentation" onClick={()=>setSelected(null)}><article className="profile-sheet" role="dialog" aria-modal="true" aria-label={`Портфолио ${active.full_name}`} onClick={(e)=>e.stopPropagation()}><button className="sheet-close" type="button" onClick={()=>setSelected(null)}>×</button><div className="profile-head"><div className="avatar-placeholder large">{active.full_name.slice(0,1)}</div><div><span className="eyebrow">Ученик академии</span><h2>{active.full_name}</h2><p>{active.metro||'Москва'}</p></div></div>{active.about_me&&<p className="profile-about">{active.about_me}</p>}{active.teachers?.length&&<p className="muted">Преподаватели: {active.teachers.map((t)=>t.full_name).join(', ')}</p>}<div className="portfolio-works full">{(works[active.id]||[]).map((work)=><article className="portfolio-work" key={work.id}><ApiImage src={workImage(work)} apiPath={!workImage(work)&&work.file_id?`/guest/homeworks/${work.id}/file`:null} alt={work.haircut_name||'Работа ученика'}/><div><strong>{work.haircut_name||'Учебная работа'}</strong><span>Урок {work.lesson_number||'бонус'} {work.rating?`· ${'★'.repeat(work.rating)}`:''}</span>{work.text_content&&<p>{work.text_content}</p>}{work.comment&&<blockquote>{work.comment}</blockquote>}</div></article>)}</div></article></div>}
  </section>
}
