import { FormEvent, useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { api } from '../api/client'
import { getMaxUserId } from '../platform/max'
import { useAuth } from '../features/auth/AuthProvider'
import { ApiImage } from '../components/ApiImage'

type Homework = { id: number; haircut_name?: string | null; text_content?: string | null; file_id?: string | null; file_url?: string | null; status: string; lesson_number?: number | null }
type Comment = { id: number; text_content: string; author_role: string; first_name?: string | null; last_name?: string | null }
const safeImages = new Set(['demo-homework-crop.png', 'demo-homework-fade.png', 'demo-homework-beard.png'])

export function HomeworkDetailPage() {
  const { session } = useAuth(); const { id } = useParams(); const maxUserId = getMaxUserId(); const [homework, setHomework] = useState<Homework | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [text, setText] = useState(''); const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [commentText, setCommentText] = useState(''); const [revisionText, setRevisionText] = useState(''); const [revisionFile,setRevisionFile]=useState<File|null>(null)
  const load = async () => { if (!id || !maxUserId) return; const response = await api.get(`/homeworks/${id}`, { params: { max_user_id: maxUserId } }); const data = response.data?.data; setHomework(data?.homework || null); setComments(data?.comments || []); setTitle(data?.homework?.haircut_name || ''); setText(data?.homework?.text_content || '') }
  useEffect(() => { void load() }, [id, maxUserId])
  const save = async (event: FormEvent) => { event.preventDefault(); if (!id || !maxUserId) return; await api.patch(`/student/homeworks/${id}`, { max_user_id: maxUserId, haircut_name: title, text_content: text }); setMessage('Изменения сохранены.'); void load() }
  const addComment = async (event: FormEvent) => { event.preventDefault(); if (!id || !commentText.trim()) return; await api.post(`/homeworks/${id}/comments`, { max_user_id: maxUserId, text: commentText.trim() }); setCommentText(''); setMessage('Комментарий добавлен.'); void load() }
  const submitRevision = async (event: FormEvent) => { event.preventDefault(); if (!id || !revisionText.trim()) return; let fileId:string|undefined; if(revisionFile){const form=new FormData();form.append('file',revisionFile);const uploaded=await api.post('/files/revision',form,{params:{max_user_id:maxUserId},headers:{'Content-Type':'multipart/form-data'}});fileId=uploaded.data?.data?.file_id} await api.post(`/student/homeworks/${id}/revision`, { max_user_id: maxUserId, text: revisionText.trim(), file_id:fileId }); setRevisionText(''); setRevisionFile(null); setMessage('Исправленная работа отправлена преподавателю.'); void load() }
  if (!homework) return <p className="state-message">Загружаем работу…</p>
  const image=homework.file_url||(homework.file_id&&safeImages.has(homework.file_id)?`/${homework.file_id}`:null)
  return <section><div className="section-heading"><div><span className="eyebrow">Урок {homework.lesson_number || 'бонус'}</span><h2>{homework.haircut_name || 'Домашнее задание'}</h2></div></div><ApiImage className="detail-photo" src={image} apiPath={!image&&homework.file_id?`/homeworks/${homework.id}/file`:null} alt={homework.haircut_name || 'Работа'}/><p className="muted">Статус: {homework.status}</p>{session?.role === 'student' && <form className="tool-form" onSubmit={save}><label>Название<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><label>Описание<textarea value={text} onChange={(event) => setText(event.target.value)} required /></label><button className="button" type="submit">Сохранить изменения</button></form>}{message && <p className="success">{message}</p>}<h3>Комментарии</h3><div className="student-list">{comments.map((comment) => <article className="student-row" key={comment.id}><strong>{comment.author_role === 'teacher' ? 'Преподаватель' : 'Ученик'}</strong><p>{comment.text_content}</p></article>)}{!comments.length && <p className="muted">Комментариев пока нет.</p>}</div><form className="tool-form" onSubmit={addComment}><textarea value={commentText} onChange={(event) => setCommentText(event.target.value)} placeholder="Добавить комментарий" required /><button className="button" type="submit">Комментировать</button></form>{session?.role === 'student' && homework.status === 'revision' && <form className="tool-form" onSubmit={submitRevision}><h3>Ответ на доработку</h3><textarea value={revisionText} onChange={(event) => setRevisionText(event.target.value)} placeholder="Что исправлено" required /><label className="file-picker compact"><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,application/pdf" onChange={(e)=>setRevisionFile(e.target.files?.[0]||null)}/><strong>{revisionFile?revisionFile.name:'Приложить исправленный файл'}</strong></label><button className="button primary" type="submit">Отправить исправление</button></form>}</section>
}
